server.port=8080

spring.application.name=ine5417
spring.application.version=1.0.0-rc.1
spring.config.import=optional:file:.env[.properties]

# PostgresSQL
spring.datasource.url=${DATABASE_DRIVER}://${DATABASE_HOST}:${DATABASE_PORT:-5432}/${DATABASE_DB}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
